#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC="/usr/local/src"

VERSION="6.0.2"
URL="http://sourceforge.net/projects/twiki/files/TWiki%20for%20all%20Platforms"

dl $URL/TWiki-$VERSION/TWiki-$VERSION.tgz $SRC

