#!/bin/sh -ex

SRC=/usr/local/src
WEBROOT=/var/www/twiki

# unpack twiki, overlay twiki configuration
tar -zxf $SRC/TWiki-*.tgz -C $(dirname $WEBROOT)
cp -TdR $SRC/twiki.overlay $WEBROOT

# workaround insecure dependency in require while running with -T switch
sed -i "s|\-wT|-w|" $WEBROOT/bin/configure

chown -R www-data:www-data $WEBROOT

# cron jobs
echo "
0 * * * * (cd $WEBROOT/bin && ./statistics >/dev/null 2>&1)
0 0 * * * (cd $WEBROOT/bin && $WEBROOT/tools/tick_twiki.pl)
0,15,30,45 * * * * (cd $WEBROOT/bin && $WEBROOT/tools/mailnotify -q)
" | crontab -u www-data -

# disable turnkey-credit in popup
CSS=$WEBROOT/pub/TWiki/TinyMCEPlugin/tinymce/jscripts/tiny_mce/themes/advanced/skins/default/dialog.css
echo "#turnkey-credit { display: none; }" >> $CSS

# apache configuration
a2dissite 000-default
a2enmod cgid
a2ensite twiki

# cleanup
rm -rf $SRC/Twiki*
rm -rf $SRC/twiki*
